@startuml SolidFI_Level0

legend top center
  SolidFI Level 0
  Scott Tringali
end legend

interface Operation<T> {
  execute();
}

interface Predicate<T> {
  {abstract} decide(T): boolean;
}

interface Composite<T, U> {
  {abstract} dispatch(T): U;
}

interface Filter<T> {
  {abstract} accepts(T);
  {abstract} rejects(T);
}

class Strategy<T, U> {
  name: string;
  priority: int;
  impl: Operation;
  ' Storage of each chain or transform link (operation)
}

' Composite <|-- Filter
Composite o-- Strategy : entries
Strategy o-- Operation : impl
Filter *-- Predicate
Filter *-- Predicate

@enduml
