@startuml SolidFI_Level1

legend top right
  SolidFI Level 1
  Scott Tringali
end legend

' !include L0.puml

top to bottom direction

together {
  interface Inverter<T, U> {}
  interface Provider<T, U> {}
}

together {
  interface Converter<T, U> {
    + {abstract} accepts(T) : boolean
    + {abstract} rejects(T) : boolean
    + {abstract} fetch(T) : U
  }

  interface Transform<T> {
    + {abstract} accepts(T) : boolean
    + {abstract} rejects(T) : boolean
    + {abstract} apply(T) : T
  }

  class Chain<T, U> {
    + accepts(T) : boolean
    + rejects(T) : boolean
    + fetch(T) : U
    .. own ..
    + resolve(T) : U
    -- Composite --
    + install(priorty: int, name: string, Converter<T, U>)
    + remove(name: string)
    + replace(name: string: Converter<T, U>)
    .. note ..
    resolve() is the friendly alias for fetch().
  }

  class Pipeline<T> {
    + accepts(T) : boolean
    + rejects(T) : boolean
    + apply(T) : T
    .. own ..
    + run(T) : T
    -- Composite --
    + install(priorty: int, name: string, Converter<T, U>)
    + remove(name: string)
    + replace(name: string: Converter<T, U>)
    .. note ..
    run() is the friendly alias for apply().
  }
}

Converter <|.. Chain : "implements\nConverter<T,U>"
Transform <|.. Pipeline : "implements\nTransform<T>"

Converter <|-- Inverter
Converter <|-- Provider

Converter --o Chain : strategies
Transform --o Pipeline : strategies

@enduml